pan100_mood_log_front:
    pattern: /
    defaults: { _controller: Pan100MoodLogBundle:Default:index, _locale: nb}

pan100_mood_log_report:
    pattern: /report
    defaults: { _controller: Pan100MoodLogBundle:Report:index, _locale: nb}