_front:
    pattern: /
    defaults: { _controller: Pan100MoodLogBundle:Default:index, _locale: nb}

_report:
    pattern: /report
    defaults: { _controller: Pan100MoodLogBundle:Report:index, _locale: nb}

_report_charttest:
    pattern: /report/chart
    defaults: { _controller: Pan100MoodLogBundle:Report:chart, _locale: nb}

_report_lastWeek:
    pattern: /report/lastweek
    defaults: { _controller: Pan100MoodLogBundle:Report:lastWeek, _locale: nb}

_report_fromFirst:
    pattern: /report/fromfirst/
    defaults: { _controller: Pan100MoodLogBundle:Report:fromFirst, _locale: nb}