_front:
    pattern: /
    defaults: { _controller: Pan100MoodLogBundle:Default:index, _locale: nb}

_admin:
    pattern: /admin/
    defaults: { _controller: Pan100MoodLogBundle:Admin:index, _locale: nb }

_report:
    pattern: /report
    defaults: { _controller: Pan100MoodLogBundle:Report:index, _locale: nb}

_report_charttest:
    pattern: /report/chart
    defaults: { _controller: Pan100MoodLogBundle:Report:chart, _locale: nb}

_report_lastWeek:
    pattern: /report/lastweek
    defaults: { _controller: Pan100MoodLogBundle:Report:lastWeek, _locale: nb}

_report_fromFirst:
    pattern: /report/fromfirst/{username}
    defaults: { _controller: Pan100MoodLogBundle:Report:fromFirst, username:self, _locale: nb}

_day:
    pattern:     /day/{date}
    defaults: { _controller: Pan100MoodLogBundle:Day:index, date:today }
    requirements:
        _format:  html|json
        _method:  GET

_day_post:
    pattern:     /day/{date}
    defaults: { _controller: Pan100MoodLogBundle:Day:post, date:today }
    requirements: 
        _format:  html|json
        _method:  POST|GET
_day_delete:
    pattern:     /day/{date}
    defaults: { _controller: Pan100MoodLogBundle:Day:delete, date:today }
    requirements: 
        _format:  html|json
        _method:  DELETE
