pan100_mood_log_front:
    pattern: /
    defaults: { _controller: Pan100MoodLogBundle:Default:index, _locale: nb}

pan100_mood_log_report:
    pattern: /report
    defaults: { _controller: Pan100MoodLogBundle:Report:index, _locale: nb}

pan100_mood_log_report_charttest:
    pattern: /report/chart
    defaults: { _controller: Pan100MoodLogBundle:Report:chart, _locale: nb}

pan100_mood_log_chart_lastWeek:
    pattern: /report/lastweek
    defaults: { _controller: Pan100MoodLogBundle:Report:lastWeek, _locale: nb}

pan100_mood_log_chart_fromFirst:
    pattern: /report/fromfirst/
    defaults: { _controller: Pan100MoodLogBundle:Report:fromFirst, _locale: nb}