Pan100\MoodLogBundle\Entity\Day:
    properties:
        date:
            - Date: ~
            - NotBlank: ~
        moodHigh:
            - Range:
                min: 0
                max: 100
                minMessage: Humør høy må være mellom 0 og 100
                maxMessage: Humør høy må være mellom 0 og 100     
        constraints:
            - Callback:
                methods:   [isHighLowCorrect]